# Generated by Django 5.2.17 on 2026-08-14 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id_pergunta', models.AutoField(primary_key=True, serialize=False)),
                ('enunciado', models.TextField(verbose_name='Enunciado')),
                ('explicacao', models.TextField(verbose_name='Explicação')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id_quiz', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('nivel', models.CharField(max_length=20, verbose_name='Nível')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=255, verbose_name='Senha')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id_alternativa', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=255, verbose_name='Texto')),
                ('correta', models.BooleanField(default=False, verbose_name='É Correta')),
                ('pergunta', models.ForeignKey(db_column='id_pergunta', on_delete=django.db.models.deletion.CASCADE, to='app.pergunta', verbose_name='Pergunta')),
            ],
            options={
                'verbose_name': 'Alternativa',
                'verbose_name_plural': 'Alternativas',
            },
        ),
        migrations.AddField(
            model_name='pergunta',
            name='quiz',
            field=models.ForeignKey(db_column='id_quiz', on_delete=django.db.models.deletion.CASCADE, to='app.quiz', verbose_name='Quiz'),
        ),
        migrations.CreateModel(
            name='TentativaQuiz',
            fields=[
                ('id_tentativa', models.AutoField(primary_key=True, serialize=False)),
                ('pontuacao', models.IntegerField(verbose_name='Pontuação')),
                ('data_realizacao', models.DateField(auto_now_add=True, verbose_name='Data de Realização')),
                ('quiz', models.ForeignKey(db_column='id_quiz', on_delete=django.db.models.deletion.CASCADE, to='app.quiz', verbose_name='Quiz')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Tentativa do Quiz',
                'verbose_name_plural': 'Tentativas dos Quizzes',
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id_denuncia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_golpe', models.CharField(max_length=100, verbose_name='Tipo do Golpe')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_registro', models.DateField(auto_now_add=True, verbose_name='Data do Registro')),
                ('status', models.CharField(default='Pendente', max_length=20, verbose_name='Status')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Denúncia',
                'verbose_name_plural': 'Denúncias',
            },
        ),
    ]
